### ISSUE TITLE
API Content-Type set to 'text/html'

### ISSUE THREAD

**Issue by RichDonnellan** [dermstore-com/FrontEndChallenge#1]
The URL endpoint supplied has its `Content-Type` set to `text/html` instead of `application/json`. This prevents any type of data fetching (TypeError).

![image](https://user-images.githubusercontent.com/7773718/63897720-0b702400-c9ab-11e9-869e-a570cfa630b0.png)

**Comment by JoshuaHuber** [comment]
Good catch.  That should be fixed now.

**Comment by RichDonnellan** [comment]
@JoshuaHuber I'm still getting the same result.
